name = 'Eleglite'
license = 'MIT'
licenselink = 'https://github.com/flynnoct/hugo-theme-eleglite/LICENSE'
description = 'A minimal yet elegant theme for Hugo.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/flynnoct/hugo-theme-eleglite'

# If you have a running demo of the theme
demosite = 'https://blog.flynnoct.com'

# Taxonomy terms
tags = ['blog', 'minimal', 'light', 'dark', 'english', 'chinese']
features = []

# If the theme has a single author
[author]
  name = 'Flynn Wang'
  homepage = 'https://blog.flynnoct.com'

# If porting an existing theme
[original]
  author = 'Name of original author'
  homepage = 'Website of original author'
  repo = 'https://github.com/owner/repo'